### ISSUE TITLE
请问 “python 关键字”的变量名是什么？

### ISSUE THREAD

**Issue by Azureki** [taigacute/gruvbox9#1]
想要修改 `python` 中和`关键字`（`def, return, import, break` 等等）有关的配置。但是不知道变量名是什么。
试了`pythonKeyword`，无效。

`Keyword` 也试了，无效。

好像也不止和theme有关？和python提供的关键字也有关？
我没做过theme，不太清楚，请指教。

**Comment by taigacute** [comment]
需要装个python 高亮的插件. python-syntax

**Comment by taigacute** [comment]
我的是这样的。你看看。
![1](https://user-images.githubusercontent.com/41671631/59502370-3381d800-8ed0-11e9-9f3c-9ef6425b8bca.png)

**Comment by Azureki** [comment]
谢谢指教，在您说的 [python-syntax插件的65行](https://github.com/vim-python/python-syntax/blob/master/syntax/python.vim#L65) 找到了和python关键字有关的变量。

**Comment by taigacute** [comment]
@Azureki   我的配置 F10 会直接打印当前光标所在的syntax group

**Comment by Azureki** [comment]
嗯。试了一下，确实可以。
