### ISSUE TITLE
如何更改lightline在normal模式时的颜色？

### ISSUE THREAD

**Issue by Azureki** [taigacute/gruvbox9#3]
不太喜欢这种黄色，在主题文件里以`normalmode`为关键字搜索，找到两处。
删除这两行，复制`insertmode`，把名字改成`normalmode`，再打开，`normalmode`的颜色不变。

唔，难道不止这两个地方会影响到lightline？

**Comment by taigacute** [comment]
lightline 我好想没加黄色。贴个图我看看哪里的颜色

**Comment by Azureki** [comment]
https://github.com/taigacute/gruvbox9/blob/master/Readme.md#lightline
就这里的normalmode

**Comment by taigacute** [comment]
@Azureki   那是绿色  `let s:p.normal.left = [ [ s:bg0, s:green, 'bold' ]`  替换green为你喜欢的颜色就可以了 。close

**Comment by Azureki** [comment]
好，是绿色，感谢。

原来我改的那里真的错了啊…
