### ISSUE TITLE
Ale warning sign no color

### ISSUE THREAD

**Issue by mihaelartz** [taigacute/gruvbox9#5]
![2019-06-22-103926_1680x1050_scrot](https://user-images.githubusercontent.com/29631158/59961589-0d64c500-94da-11e9-91d1-80139820a5af.png)
![2019-06-22-103935_1680x1050_scrot](https://user-images.githubusercontent.com/29631158/59961590-0d64c500-94da-11e9-9c33-9fd10048d8ac.png)

**Comment by taigacute** [comment]
@mihaelartz   you should set `let g:gruvbox_plugin_hi_groups = 1`
